export const medians = [
  {
    name: "Identify Errors:",
    median: 1.999976,
    lo: "Easy",
    hi: "Hard",
  },
  {
    name: "Fix Errors:",
    median: 2,
    lo: "Easy",
    hi: "Hard",
  },
  {
    name: "Easier to Fix:",
    median: 1.999969,
    lo: "Toolbar",
    hi: "Gesture",
  },
  {
    name: "Faster to Fix:",
    median: 2.500045,
    lo: "Toolbar",
    hi: "Gesture",
  },
  {
    name: "Easier on Phone:",
    median: 1.500022,
    lo: "Toolbar",
    hi: "Gesture",
  },
  {
    name: "Easier on Tablet:",
    median: 2.99998,
    lo: "Toolbar",
    hi: "Gesture",
  },
  {
    name: "Device Preference:",
    median: 4.500007,
    lo: "Phone",
    hi: "Tablet",
  },
];

export const values = [
  { value: 2, name: "Identify Errors:", id: "P1" },
  { value: 2, name: "Fix Errors:", id: "P1" },
  { value: 3, name: "Easier to Fix:", id: "P1" },
  { value: 4, name: "Faster to Fix:", id: "P1" },
  { value: 2, name: "Easier on Phone:", id: "P1" },
  { value: 5, name: "Easier on Tablet:", id: "P1" },
  { value: 5, name: "Device Preference:", id: "P1" },
  { value: 2, name: "Identify Errors:", id: "P2" },
  { value: 3, name: "Fix Errors:", id: "P2" },
  { value: 4, name: "Easier to Fix:", id: "P2" },
  { value: 5, name: "Faster to Fix:", id: "P2" },
  { value: 5, name: "Easier on Phone:", id: "P2" },
  { value: 5, name: "Easier on Tablet:", id: "P2" },
  { value: 5, name: "Device Preference:", id: "P2" },
  { value: 2, name: "Identify Errors:", id: "P3" },
  { value: 2, name: "Fix Errors:", id: "P3" },
  { value: 2, name: "Easier to Fix:", id: "P3" },
  { value: 1, name: "Faster to Fix:", id: "P3" },
  { value: 2, name: "Easier on Phone:", id: "P3" },
  { value: 1, name: "Easier on Tablet:", id: "P3" },
  { value: 5, name: "Device Preference:", id: "P3" },
  { value: 3, name: "Identify Errors:", id: "P4" },
  { value: 3, name: "Fix Errors:", id: "P4" },
  { value: 2, name: "Easier to Fix:", id: "P4" },
  { value: 2, name: "Faster to Fix:", id: "P4" },
  { value: 4, name: "Easier on Phone:", id: "P4" },
  { value: 1, name: "Easier on Tablet:", id: "P4" },
  { value: 5, name: "Device Preference:", id: "P4" },
  { value: 2, name: "Identify Errors:", id: "P5" },
  { value: 2, name: "Fix Errors:", id: "P5" },
  { value: 4, name: "Easier to Fix:", id: "P5" },
  { value: 4, name: "Faster to Fix:", id: "P5" },
  { value: 4, name: "Easier on Phone:", id: "P5" },
  { value: 5, name: "Easier on Tablet:", id: "P5" },
  { value: 5, name: "Device Preference:", id: "P5" },
  { value: 1, name: "Identify Errors:", id: "P6" },
  { value: 3, name: "Fix Errors:", id: "P6" },
  { value: 3, name: "Easier to Fix:", id: "P6" },
  { value: 4, name: "Faster to Fix:", id: "P6" },
  { value: 4, name: "Easier on Phone:", id: "P6" },
  { value: 4, name: "Easier on Tablet:", id: "P6" },
  { value: 4, name: "Device Preference:", id: "P6" },
  { value: 2, name: "Identify Errors:", id: "P7" },
  { value: 3, name: "Fix Errors:", id: "P7" },
  { value: 4, name: "Easier to Fix:", id: "P7" },
  { value: 5, name: "Faster to Fix:", id: "P7" },
  { value: 3, name: "Easier on Phone:", id: "P7" },
  { value: 2, name: "Easier on Tablet:", id: "P7" },
  { value: 4, name: "Device Preference:", id: "P7" },
  { value: 3, name: "Identify Errors:", id: "P8" },
  { value: 1, name: "Fix Errors:", id: "P8" },
  { value: 2, name: "Easier to Fix:", id: "P8" },
  { value: 4, name: "Faster to Fix:", id: "P8" },
  { value: 2, name: "Easier on Phone:", id: "P8" },
  { value: 5, name: "Easier on Tablet:", id: "P8" },
  { value: 5, name: "Device Preference:", id: "P8" },
  { value: 2, name: "Identify Errors:", id: "P9" },
  { value: 3, name: "Fix Errors:", id: "P9" },
  { value: 2, name: "Easier to Fix:", id: "P9" },
  { value: 4, name: "Faster to Fix:", id: "P9" },
  { value: 1, name: "Easier on Phone:", id: "P9" },
  { value: 4, name: "Easier on Tablet:", id: "P9" },
  { value: 4, name: "Device Preference:", id: "P9" },
  { value: 2, name: "Identify Errors:", id: "P10" },
  { value: 2, name: "Fix Errors:", id: "P10" },
  { value: 1, name: "Easier to Fix:", id: "P10" },
  { value: 1, name: "Faster to Fix:", id: "P10" },
  { value: 1, name: "Easier on Phone:", id: "P10" },
  { value: 1, name: "Easier on Tablet:", id: "P10" },
  { value: 5, name: "Device Preference:", id: "P10" },
  { value: 2, name: "Identify Errors:", id: "P11" },
  { value: 2, name: "Fix Errors:", id: "P11" },
  { value: 1, name: "Easier to Fix:", id: "P11" },
  { value: 1, name: "Faster to Fix:", id: "P11" },
  { value: 1, name: "Easier on Phone:", id: "P11" },
  { value: 1, name: "Easier on Tablet:", id: "P11" },
  { value: 4, name: "Device Preference:", id: "P11" },
  { value: 1, name: "Identify Errors:", id: "P12" },
  { value: 3, name: "Fix Errors:", id: "P12" },
  { value: 2, name: "Easier to Fix:", id: "P12" },
  { value: 3, name: "Faster to Fix:", id: "P12" },
  { value: 1, name: "Easier on Phone:", id: "P12" },
  { value: 3, name: "Easier on Tablet:", id: "P12" },
  { value: 3, name: "Device Preference:", id: "P12" },
  { value: 2, name: "Identify Errors:", id: "P13" },
  { value: 2, name: "Fix Errors:", id: "P13" },
  { value: 1, name: "Easier to Fix:", id: "P13" },
  { value: 1, name: "Faster to Fix:", id: "P13" },
  { value: 1, name: "Easier on Phone:", id: "P13" },
  { value: 1, name: "Easier on Tablet:", id: "P13" },
  { value: 5, name: "Device Preference:", id: "P13" },
  { value: 3, name: "Identify Errors:", id: "P14" },
  { value: 3, name: "Fix Errors:", id: "P14" },
  { value: 2, name: "Easier to Fix:", id: "P14" },
  { value: 2, name: "Faster to Fix:", id: "P14" },
  { value: 1, name: "Easier on Phone:", id: "P14" },
  { value: 1, name: "Easier on Tablet:", id: "P14" },
  { value: 1, name: "Device Preference:", id: "P14" },
  { value: 4, name: "Identify Errors:", id: "P15" },
  { value: 5, name: "Fix Errors:", id: "P15" },
  { value: 1, name: "Easier to Fix:", id: "P15" },
  { value: 1, name: "Faster to Fix:", id: "P15" },
  { value: 1, name: "Easier on Phone:", id: "P15" },
  { value: 1, name: "Easier on Tablet:", id: "P15" },
  { value: 5, name: "Device Preference:", id: "P15" },
  { value: 1, name: "Identify Errors:", id: "P16" },
  { value: 3, name: "Fix Errors:", id: "P16" },
  { value: 2, name: "Easier to Fix:", id: "P16" },
  { value: 2, name: "Faster to Fix:", id: "P16" },
  { value: 1, name: "Easier on Phone:", id: "P16" },
  { value: 4, name: "Easier on Tablet:", id: "P16" },
  { value: 5, name: "Device Preference:", id: "P16" },
  { value: 3, name: "Identify Errors:", id: "P17" },
  { value: 2, name: "Fix Errors:", id: "P17" },
  { value: 2, name: "Easier to Fix:", id: "P17" },
  { value: 2, name: "Faster to Fix:", id: "P17" },
  { value: 1, name: "Easier on Phone:", id: "P17" },
  { value: 3, name: "Easier on Tablet:", id: "P17" },
  { value: 2, name: "Device Preference:", id: "P17" },
];
