import re
import json
import os

def extract_data():
    html_path = 'original_visualization/desktop.html'
    output_path = 'src/data.ts'

    with open(html_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Regex to find the JSON object assigned to var spec
    match = re.search(r'var spec = ({.*?});', content, re.DOTALL)
    if not match:
        print("Could not find spec JSON in html file.")
        return

    json_str = match.group(1)
    try:
        data = json.loads(json_str)
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        return

    # Extract dataset
    dataset_key = "data-b0fe595546d47c5085f225c35730172c"
    if "datasets" not in data or dataset_key not in data["datasets"]:
        print("Dataset not found in JSON.")
        return

    raw_data = data["datasets"][dataset_key]
    
    # Filter out GOOG
    filtered_data = [d for d in raw_data if d.get('symbol') != 'GOOG']

    # Generate TypeScript file
    ts_content = f"""// Generated by extract_data.py
export interface StockData {{
  symbol: string;
  date: string;
  price: number;
}}

export const stockData: StockData[] = {json.dumps(filtered_data, indent=2)};
"""

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(ts_content)

    print(f"Data extracted and saved to {output_path}")

if __name__ == "__main__":
    extract_data()
